orbs:
  heroku-container: pbrisbin/heroku-container@1.0.0
version: 2.1
workflows:
  build_and_release:
    jobs:
      - heroku-container/push-and-release:
          app-name: security-cam-go
          before-build:
            - run: |
                cat >Dockerfile.web \<<EOM
                FROM ...
                CMD ...
                EOM

                cat >Dockerfile.worker \<<EOM
                FROM ...
                CMD ...
                EOM
          process-types: web worker
          recursive: true
